"""Add news aggregation tables

Revision ID: 45ff66ae7419
Revises: 
Create Date: 2025-07-27 21:23:44.953937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ff66ae7419'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('additional_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregated_news_id'), 'aggregated_news', ['id'], unique=False)
    op.create_table('rss_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_rss_sources_id'), 'rss_sources', ['id'], unique=False)
    op.create_table('raw_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rss_source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rss_source_id'], ['rss_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_news_id'), 'raw_news', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_news_id'), table_name='raw_news')
    op.drop_table('raw_news')
    op.drop_index(op.f('ix_rss_sources_id'), table_name='rss_sources')
    op.drop_table('rss_sources')
    op.drop_index(op.f('ix_aggregated_news_id'), table_name='aggregated_news')
    op.drop_table('aggregated_news')
    # ### end Alembic commands ###
